plugins {
    id 'base'
}

task zipModule(type: Zip) {
    archiveFileName = 'ToastMagers-release.zip'
    destinationDirectory = file("${rootDir}/out")

    // Include standard Magisk module template
    from('magisk_template') {
        include '**/*'
    }

    // Prepare system/usr/share/toast_magers directory if we have configurations
    into('system') {
        // Just as an example or placeholder for compiled binaries/files
    }
}

clean {
    delete "${rootDir}/out"
}
